// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKeBHhN3D_6CQPZbyf6KLfWG8Sugix5GA',
    appId: '1:23338177272:web:da5df60139f41b749be10d',
    messagingSenderId: '23338177272',
    projectId: 'test-login-a031a',
    authDomain: 'test-login-a031a.firebaseapp.com',
    storageBucket: 'test-login-a031a.firebasestorage.app',
    measurementId: 'G-T5XWF8L7Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr9Rq2YudlH5-0L7RrUNHUgVJT4HHd2hc',
    appId: '1:23338177272:android:b34cb4930bd60afc9be10d',
    messagingSenderId: '23338177272',
    projectId: 'test-login-a031a',
    storageBucket: 'test-login-a031a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUj5Ct_7NCTN9SPAN5I_fKL156Ew9RZY4',
    appId: '1:23338177272:ios:f2c9b4cab41dabe09be10d',
    messagingSenderId: '23338177272',
    projectId: 'test-login-a031a',
    storageBucket: 'test-login-a031a.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );
}
